sudo: false
language: node_js
node_js:
  - stable

cache: npm

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: dm.bilibili.one
  keep_history: true
  on:
    branch: master 